-- public.followers definition

-- Drop table

-- DROP TABLE public.followers;

CREATE TABLE public.followers (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	follower_id int8 NULL,
	user_id int8 NULL
);