version: "3.7"

services:
  postgres_social:
    container_name: postgres_social
    image: postgres:14
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: social
    ports:
      - "5435:5432"
    networks:
      - quarkus

  quarkus_social:
    container_name: quarkus-social
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus/quarkus-social-jvm
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://host.docker.internal:5435/postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres_social
    networks:
      - quarkus

networks:
  quarkus:
    driver: bridge